### ISSUE TITLE
Hitachi heat pump not appearing as device

### ISSUE THREAD

**Issue by PdB30000** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#11]
Thanks for making this local API !!!

I have an HITACHI heat pump connected with my TAHOMA system.

I can log and get devices list from the API, but the HITACHI pump params doesn't appear.

Am I missing something?

**Comment by iMicknl** [comment]
Same request here; it would be great if all devices are supported via the local API (including climate / water heaters). Otherwise (in our case Home Assistant) users still need to have a cloud connection (with event listener..) and a local API connection (with event listener..).

**Comment by AdyRock** [comment]
Same goes for Somfy Protect when connected to Tahoma. I can control it via Tahoma using the cloud connection but it doesn't appear in the get devices list for the local API and trying to control it returns error 400.
So I will have to continue to use the cloud API so that I can control my Somfy One alarm.

**Comment by llavorel-somfy** [comment]
Hi

Hitachi gateways are not supported by TaHoma switch.
The cost for this feature is too big regarding the number of products and the direction we are taking with our partner Hitachi.
