### ISSUE TITLE
Please add support for the `/setup/devices/states/refresh` endpoint

### ISSUE THREAD

**Issue by fetzerch** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#26]
There are some devices like the *Dexxo 1000 io* that don't send state update events when operated by a physically connected button. Therefore the official app & *tahomalink.com* sends a POST request on startup to the `/setup/devices/states/refresh` endpoint that triggers all these devices to send their state updates to the gateway.

It would be nice to be able to trigger this refresh on a regular interval using the local connection.

The `/setup/devices/states/refresh` endpoint is not listed in the [swagger documentation](https://somfy-developer.github.io/Somfy-TaHoma-Developer-Mode/) and an attempt to call it leads to an `Unknown object.` error. The [cloud API docs](https://tahomalink.com/enduser-mobile-web/enduserAPI/doc) lists this endpoint and an additional `/setup/devices/{deviceURL}/states/refresh` that would be helpful for the usecase as well.

Could you please add support for these endpoints?

**Note**

I noticed that this might be related to #7 which discusses the `Unknown object.` error for the `/setup/devices/{deviceUrl}/states` endpoint.

**Steps to reproduce:**

```
$ curl --insecure -X POST --header "Content-Length: 0" --header "Authorization: Bearer XXX" https://gateway-XXXX-XXXX-XXXX.local:8443/enduser-mobile-web/1/enduserAPI/setup/devices/states/refresh | jq

{
  "error": "Unknown object.",
  "errorCode": "UNSPECIFIED_ERROR"
}
```

**Expected result**

Being able to refresh the states and get notified about changes through the event listener.

**Environment**

- TaHoma Premium
- Firmware version: 2022.2.4-13
- Dexxo 1000 io (Firmware 5047247X47)

**Comment by fetzerch** [comment]
Meanwhile I replaced my *Dexxo Pro 1000 io* with the newer *Dexxo Smart 800 io*, but that suffers from exactly the same issue. (TaHoma Firmware: 2023.1.4-12, Motor Firmware 5156018B13).

I'm wondering if this is really the expected behavior of the Somfy io garage door motors. I think they should also send update events to the gateway if they are operated by physical buttons connected to *start* (/ *stop*).

I also noticed that `/setup` lists an `advancedRefresh` command, that is not further documented. The Gateway however responds with helpful error messages. And my understanding now is that this command can serve as a workaround:

1. This refreshes most states
```
{
  "label" : "Refresh states",
  "actions" : [ {
    "deviceURL" : "io://xxx",
    "commands" : [ {
      "name" : "advancedRefresh",
      "parameters" : [ "normal" ]
    } ]
  } ]
}
```

2. This refreshes all states
```
{
  "label" : "Refresh all states",
  "actions" : [ {
    "deviceURL" : "io://xxx",
    "commands" : [ {
      "name" : "advancedRefresh",
      "parameters" : [ "advanced" ]
    } ]
  } ]
}
```

3. This refreshes the selected states:
```
{
  "label" : "Refresh selected states",
  "actions" : [ {
    "deviceURL" : "io://xxx",
    "commands" : [ {
      "name" : "advancedRefresh",
      "parameters" : [ "custom",  ["core:OpenClosedPartialState", "core:StatusState", "core:RSSILevelState"]]
    } ]
  } ]
}
```

@vhenriet-sfy It would really be nice if you or someone else from the Somfy team could give a few more insights.
1. Could not sending updates automatically be considered a bug that Somfy could fix via firmware updates?
2. If not is there any better way than avoiding constant polling for state updates?
3. Is my understanding of `advancedRefresh` correct and do you see any negative impact when calling the method for instance every minute? (e.g. high power consumption on the engine/gateway, ...)

For completeness: My usecase is that I want to automatically open the garage door for better air ventilation when the humidity inside is higher than outside. For these kind of automations it's important to know the current actual state (open/closed)

**Comment by llavorel-somfy** [comment]
Hi @fetzerch 

What kind of physical button are you using ?

Have you registered an event listener ? If yest, are you saying that no event occurs when the Dexxo reaches a new position ?

**Comment by fetzerch** [comment]
Hi @llavorel-somfy,

I have 2 non-smart in-wall push-buttons (https://www.jung.de/en/online-catalogue/63907066/63907067/) that are wired up to *start* as shown in this picture:

![grafik](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/assets/1133994/6a4249ab-6d5e-451b-9cb9-3051a7c91941)

I do have an event listener and everything is working fine when I use the KeeGo IO remotes or the App, or the Webinterface. Then my listener gets called with the new `core:OpenClosedPartialState`. If I use the physical buttons, then the listener is not called at all. Not even after hours. That's what I meant with bug. In my opinion the motor should send the state updates to the Gateway no matter how the moving of the motor was triggered. (Actually I notice that it's just my assumption here that the motor doesn't send the state update to the Gateway. Can also be that the TaHoma just doesn't call the event listener.)

The TaHoma Webinterface works around this issue by sending `/setup/devices/states/refresh` whenever you open it. This seems to ask every connected io device to send all state updates to the Gateway and the Gateway then calls the event listeners. That's ok for an App with UI, but it doesn't work if you want to build an automation that relies on knowing the correct current open/closed state.

**Comment by llavorel-somfy** [comment]
Indeed, this is a true limitation of those devices and the way they handle wired controls. No event is generated by the motor when you are in this use case. Therefore, no event is forwarded to you listener.
At the moment there is no method to force a manual refresh. I let the "enhancement" flag to highlight the need of a new feature.

**Comment by fetzerch** [comment]
@llavorel-somfy Thanks for confirmation. Can the `advancedRefresh` command be used? see my investigation and the questions in my earlier comment: https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/26#issuecomment-1596155711

**Comment by llavorel-somfy** [comment]
Hi @fetzerch 
No, this command does not allow to adress your use case

**Comment by rwzdoorn** [comment]
Hi @llavorel-somfy I have a Somfy KeyGo IO in combination with the Dexxo Smart IO 1000 (like Fetzerch has). When We use the KeyGo it triggers the 'open' state correct, but when we use it again to close the gate, the state stays on 'open'. After 35 minutes the state is still 'open'. This should not be the case, right? Specially when using a 'IO' official key...

**Comment by llavorel-somfy** [comment]
Hi
The gateway  already follows refresh mecanisms based on legal and reasonable aspects of bandwidth usage.
We will not open such endpoint.

**Comment by webjib** [comment]
> Hi The gateway already follows refresh mecanisms based on legal and reasonable aspects of bandwidth usage. We will not open such endpoint.

You mean that the 800 MHz frequency used by Somfy should not be used too often? Why does the motor not send its status each time it's closing or opening? This is most likely a design failure: nobody at Somy imagined that users would use they physical KeyGo keys **AND** the Tahoma app at the same time?!

In matter of app design: when we open the Tahoma app, we can see for example that the gate is opened, and few seconds later, the app reports that the gate is actually closed. That's confusing. Somy should fix that, by allowing the Tahoma box t ores quest the status itself, and not only when the user opens the app.

**Comment by erugeri** [comment]
> Hi The gateway already follows refresh mecanisms based on legal and reasonable aspects of bandwidth usage. We will not open such endpoint.

Hi @llavorel-somfy , I don't understand the "bandwidth usage" point. Any endpoint could be abused, moreover, the tahoma API seems local so it's the user own problem if one wants to do stupid things which we can already do calling /setup or any other endpoint.
However, if you really still find the bandwidth risk too important, you could implement a rate limiter and reply a "HTTP 428 Too many requests" when the endpoint is too frequently called.

Imho, there is a bug as the garage door motor sometimes doesn't report its position when changed from a Keygo. 

I think Somfy could either:
- fix the bug and have the motor always report the right position
- or at least offer a way for users to ask the motor to refresh it

My use case is to ventilate the garage by switching the garage door from closed to partial when absolute humidity is lower outside. 
Once every hour, the code checks humidity both inside and outside and **only if the door is closed** switches it to partial.
However, sometimes the door has been opened, but the API replies that it is closed so the order to put it in partial is sent which lower the door. This is _dangerous_ as someone could be inside, or a car/bike/person could be moving at the same time. 
The position check should be reliable (or at least a way to refresh it beforehand could make it so).
 
It seems the Somfy app is able to refresh positions at launch, could you please open (and document) the API call so that we can respectfully call it when needed? 
In my opinion, that seems fair to ask as apparently Somfy sees itself the need in its app too so why not allow users to use it?

Thanks for your help in improving Somfy products. Don't hesitate if you have questions.

**Comment by llavorel-somfy** [comment]
Hello @erugeri 

This is not a bug, this generation of motor does not report state when changed from a Keygo.

Indeed, the Somfy app refreshes when it is opened by the user. Which is truely different than polling every x sec to refresh.

**Comment by erugeri** [comment]
Let's call it a 'feature' (or lack of) if it's not a bug then 🙃
In my use case this refresh endpoint would be called 2 times per day, right before moving the door to check its position for safety, which is very different from a polling behavior. 
Anyway, I don't understand why you don't want to open this endpoint in order to fix the 'feature' and allow us to know the real position of an equipment we bought and we thought was 'smart'. 
I chose IO devices over RTS because they were supposed to report their state.
I don't mind having to find a workaround and refresh it myself when needed but I don't understand that an equipment that is supposed to report its state but has a 'feature' and doesn't do it, somfy knows it and use a workaround to make it look right but doesn't want to open this workaround to its paying users...
Maybe I missed something....

**Comment by martinberanek** [comment]
The somfy garagedoor motors are neverending story. I also chozen IO over RTS because of it's bidirectional nature and ends in this 3 year old thread full of frustrations.

As SOMFY is not able to get their garage doors work with Apple Homekit, I got around it using Node-RED with homekit plugin and I have fully functional garage doors in my Apple ecosystem - except the case when I use the physical button inside the garage). So for example when I'm near the house, I see the garage door control widget in my Apple Carplay... Why this cannot work natively? 

I will probably replace the physical button with Somfy Transmitter or some other solution using the API (e.g. Shelly).

I have a ritual to check every year the state of this issue. As professional software developer, I'm just crying...

**Comment by qelanhari** [comment]
Using a keygo would be the same as the physical button.
I am using a hue dimmer remote with HomeKit and the api...

**Comment by webjib** [comment]
> I have a ritual to check every year the state of this issue. As professional software developer, I'm just crying...

I can’t agree more :-(

To bypass this ugly limitation, I’ve replaced my keygo remotes with bluetooth remotes, connected to my Home Assistant. But I’m not really satisfied with this solution because of the limited radio range of Bluetooth compared to Keygo.

The IO motor is clearly not bidirectional in its implementation.

**Comment by krzakx** [comment]
Hello all.
I am not super expertise in this, but this looks like the issue that I do face.

I am using HA companion app as my main controller point + naturally physical switches on wall,
My HA integration setup uses Cloud API - and still I do lack a proper freshness which is pretty much frustrating, is there any chance to improve user experience? any walkaround?

I do have side sliding gate and garage door.

**Comment by erugeri** [comment]
In case it's interesting for someone : I built a workaround using zigbee sensors : https://sonoff.tech/fr-fr/products/sonoff-senseguard-dw-gen2-zigbee-door-window-sensor-snzb-04pr2?variant=47746287239409
with the magnet on the door and the sensor on the rail I can know if the door is open or not to avoid switching to partial (to ventilate) when it's opened (which would close it on anyone that could be moving below!!)

**Comment by krzakx** [comment]
thanks for sharing - for me this is know DIY solution, hope you do use 2 such sensors one on open position and 2nd on closed position - to really be sure about state in case one sensor will hang up/fail or something.

However by choosing TaHoma Switch I was considering I am going for fully professional and validated solution paying for this extra $$$

**Comment by erugeri** [comment]
I just have one sensor on each door to detect when it's fully open. So far I never had an issue it's pretty reliable and it's basically already a redundant safeguard. 
You could totally add 2 sensors for each door for even more safety but one is already perfectly enough for me.

**Comment by martinberanek** [comment]
> However by choosing TaHoma Switch I was considering I am going for fully professional and validated solution paying for this extra $$$

@krzakx what do you mean by this? I'm ready to buy "anything" to get proper state reported in local Tahoma API.

PS: I'm directly using API from NodeRED and have Garage Door appliance in my apple home ecosystem

PS2: This is second issue, Somfy declared compatibility with Apple Home, but not about garage door ...

**Comment by krzakx** [comment]
Sorry I used misleading wording I should better say:
_However by choosing TaHoma Switch I was **expecting** I am going for fully professional and validated solution paying for this extra $$$_
