### ISSUE TITLE
Question: providing a comprehensive changelogs?

### ISSUE THREAD

**Issue by nyroDev** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#78]
Hello @Somfy-Developer

I have a Tahoma for 3 years now I think.  
Everytime I do firmware updates, I don't know what to expect, and I have actually no idea what the updates is for.

In regular user point of view, I saw no changes at all.
In developper point of view, I saw the local API changes, but it didn't change since it there (see #20)

I'm pretty sure you have many elements to update and reasons to do that, but us, as user (and/or developper) have AFAIK no idea what's going on.

In order to have more information, could it possible to provide a comprehensive changelog for every versions?
Maybe on this github repo?

It will help us to know if we could except new features or removed features and be clearer for everybody I guess.

Thanks.

**Comment by Quentame** [comment]
Hi !

Also, provide the new version name as string.

Both will help for https://github.com/home-assistant/core/pull/83430

Exemples:
Endpoint `/last_version`:
```json
{
    "name" : "2022.12.0",
    "released_at": "2022-12-01T00:00:00Z",
    "notes": "This release adds Matter support to all of our products! Enjoy 🥳"
}
```

An historical version endpoint `/versions` for people on very old version could get the history from the last to his version:
```json
{
    "2022.12.0": {
        "name" : "2022.12.0",
        "released_at": "2022-12-01T00:00:00Z",
        "notes": "This release adds Matter support to all of our products! Enjoy 🥳"
    },
    "2022.11.3": {
        "name" : "2022.11.3",
        "released_at": "2022-11-18T00:00:00Z",
        "notes": "- Fixes heating temperature on our new heater\n- Fixes connectivity issues with local API"
    },
    …
}
```
Or maybe a simple list instead of a dictionary.

The "notes" attribute could be HTML.
Maybe also add a "breaking_change" attributes so it gets highlighted by its separation of the "notes" attr.

Thanks !

**Comment by tetienne** [comment]
@llavorel-somfy @vhenriet-sfy Any update on this?

**Comment by llavorel-somfy** [comment]
Hi
Operationnaly speaking and for internal reasons, it will be too hard for us to generate such changelogs
